/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddressLookup: typeof import('./components/address/AddressLookup.vue')['default']
    HeaderButtonsComponent: typeof import('./components/HeaderButtonsComponent.vue')['default']
    MapComponent: typeof import('./components/map/mapComponent.vue')['default']
    MapPopupComponent: typeof import('./components/MapPopupComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToastComponent: typeof import('./components/ToastComponent.vue')['default']
  }
}
