// <auto-generated />
using System;
using FiberEvolutionScraper.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FiberEvolutionScraper.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251110153329_SyncModelInheritance")]
    partial class SyncModelInheritance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FiberEvolutionScraper.Api.Models.AutoRefreshInput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaSize")
                        .HasColumnType("integer");

                    b.Property<double>("CoordX")
                        .HasColumnType("double precision");

                    b.Property<double>("CoordY")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastRun")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AutoRefreshInput");
                });

            modelBuilder.Entity("FiberEvolutionScraper.Api.Models.EligibiliteFtth", b =>
                {
                    b.Property<string>("CodeImb")
                        .HasColumnType("text");

                    b.Property<int>("EtapeFtth")
                        .HasColumnType("integer");

                    b.Property<string>("FiberPointDTOSignature")
                        .HasColumnType("text");

                    b.Property<string>("Batiment")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDebutEligibilite")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CodeImb", "EtapeFtth", "FiberPointDTOSignature");

                    b.HasIndex("FiberPointDTOSignature");

                    b.ToTable("EligibiliteFtth");
                });

            modelBuilder.Entity("FiberEvolutionScraper.Api.Models.FiberPoint", b =>
                {
                    b.Property<string>("Signature")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LibAdresse")
                        .HasColumnType("text");

                    b.Property<double>("X")
                        .HasColumnType("double precision");

                    b.Property<double>("Y")
                        .HasColumnType("double precision");

                    b.HasKey("Signature");

                    b.HasIndex("Signature")
                        .IsUnique();

                    b.ToTable("FiberPoint");
                });

            modelBuilder.Entity("FiberEvolutionScraper.Api.Models.User.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UId")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FiberEvolutionScraper.Api.Models.AutoRefreshInput", b =>
                {
                    b.HasOne("FiberEvolutionScraper.Api.Models.User.UserModel", "User")
                        .WithMany("AutoRefreshs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FiberEvolutionScraper.Api.Models.EligibiliteFtth", b =>
                {
                    b.HasOne("FiberEvolutionScraper.Api.Models.FiberPoint", "FiberPoint")
                        .WithMany("EligibilitesFtth")
                        .HasForeignKey("FiberPointDTOSignature")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("FiberPoint");
                });

            modelBuilder.Entity("FiberEvolutionScraper.Api.Models.FiberPoint", b =>
                {
                    b.Navigation("EligibilitesFtth");
                });

            modelBuilder.Entity("FiberEvolutionScraper.Api.Models.User.UserModel", b =>
                {
                    b.Navigation("AutoRefreshs");
                });
#pragma warning restore 612, 618
        }
    }
}
